### PR TITLE
feat(transport): rabbitmq consumer is introduced

### PR DESCRIPTION
**Pull request by serge-medvedev**
Got inspired by [this article](https://www.instaclustr.com/post-500-nodes-high-availability-scalability-with-riemann/).
Would be glad to hear any feedback including opinions on whether it might be useful.

### CODE REVIEW

**Comment by jamtur01** [comment]
Tests would be good - https://github.com/riemann/riemann/blob/master/test/riemann/transport/opentsdb_test.clj - are examples for OpenTSDB.

**Comment by jamtur01** [comment]
I am just going to close and re-open to re-trigger the CI. Don't panic. :)

**Comment by jamtur01** [comment]
LGTM and thanks again!

**Comment by serge-medvedev** [comment]
My pleasure. Thank you, too.

**Pull request merged**
