### PR TITLE
Update to Clojure 1.11.1

### PR DESCRIPTION
**Pull request by brandonvin**
https://github.com/riemann/riemann/issues/1038

Update Clojure version to 1.11.1 in project.clj.

Initially, this caused a test to fail:

```
Testing: riemann.test-test
Running tests in: riemann.test-test
  Running test: #'riemann.test-test/only-one-tap-per-context
    FAIL
      Expected: (re-find #"Tap :foo \(.+?:\) already defined at :" err)
      Actual: (not (re-find #"Tap :foo \(.+?:\) already defined at :" Unexpected error macroexpanding riemann.test/tap at (/tmp/form-init8155462538598659347.clj:1:6476).))
  Finished test: #'riemann.test-test/only-one-tap-per-context
```

The `riemann.test/tap` macro throws a RuntimeException if a tap with the given name already exists:

https://github.com/riemann/riemann/blob/25235d3fe001be5593ee28a8daaa876d2fd561b4/src/riemann/test.clj#L64-L69

Clojure changed how errors in macroexpansion are reported - it's now a CompilerException with the original RuntimeException as a cause, so the assertion needs to pull out the `ex-cause`.

I ran tests locally by mimicking the steps in `.github/workflows/test.yaml`. If there's a way to run the Gtihub test workflow on this PR, that would be great! 🙏

### CODE REVIEW

**Comment by smortex** [comment]
Dang, CI does not currently run on PRs.  I opened #1040 to address this issue.

**Comment by jamtur01** [comment]
I don't think I can manually trigger a GH action on the branch - if you push an update it should run.

**Comment by smortex** [comment]
I am not sure that closing / reopening the PR will do the trick (since the branch has no CI bits).  I think that rebasing on top of `main` will do the trick:


```
git fetch origin       # Download the latest code we have here
git rebase origin/main # Move your commits on top of the main branch
git push -f            # Send the changes (-f is required because we re-wrote history)
```

Thanks!

**Comment by brandonvin** [comment]
Thank you for the quick change to get CI running on PRs! That's great.

I synced my fork with this repo, and that has triggered CI on the branch.

**Review by smortex — APPROVED** [review]
LGTM! :100:

**Comment by brandonvin** [comment]
Thank you @smortex and @jamtur01 for the quick feedback and help on this!

**Pull request merged**
