### PR TITLE
Updating netty to 4.1.0

### PR DESCRIPTION
**Pull request by pradeepchhetri**

### CODE REVIEW

**Comment by jamtur01** [comment]
Can you quickly share what this fixes/improves/changes? Thanks!

**Comment by pradeepchhetri** [comment]
@jamtur01 I didn't look into the details but read this blog (http://netty.io/news/2016/05/26/4-1-0-Final.html). I am still trying to figure out what is causing it to throw `OutOfMemoryError` for `jdk8`.

**Comment by jamtur01** [comment]
LGTM - @pyr ?

**Comment by jamtur01** [comment]
Go to 4.1.4 given current release? @pradeepchhetri

**Comment by pyr** [comment]
@pradeepchhetri you are saying that you are seeing OOM errors with this and a JDK8?

**Comment by pradeepchhetri** [comment]
@pyr Actually one of the Riemann tests failed in travisci when I opened the pull request with OOM errors but later it passed without any change from my side.

**Comment by jamtur01** [comment]
@pradeepchhetri I think that's unrelated to this. I've seen a few of those. But @pyr might have clearer idea.

**Comment by pyr** [comment]
Ok, then I'm inclined to have this one go in and let people who run on master report on it.

**Pull request merged**
