### PR TITLE
Mock a complete core in test mode

### PR DESCRIPTION
**Pull request by mcorbin**
Tried to do better than #821 ;)
Still testing it but everything seems to work as expected.
You can check #838 for more informations.

@aphyr What do you think about it ?

### CODE REVIEW

**Comment by mcorbin** [comment]
Could i have a review on this PR ? I would really like to know if my idea/implementation is good or not.

**Comment by mcorbin** [comment]
On hold, cf [http://irc-logs.ovh/logs/riemann-logs-17-11-06.txt](http://irc-logs.ovh/logs/riemann-logs-17-11-06.txt)

**Comment by derekchiang** [comment]
Hi @mcorbin, this looks extremely helpful; thanks for doing this.  Do you happen to have an end-to-end example of how one might use the index in tests with your code?

**Comment by mcorbin** [comment]
Hi, you have examples in #838 . I am currently rewriting this PR (cf the discussion on the irc logs), so things will probably change ;).

**Comment by mcorbin** [comment]
Closed for now, a new PR will arrive soon.

**Pull request closed without merging**
