### PR TITLE
777 test utils with fixtures

### LINKED ISSUE #777: Use `clojure.test/deftest` with `use-fixtures` instead of `riemann.test/deftest`
Hi,

There a couple problems with `riemann.test/deftest`:

1. overriding `deftest` is quite confusing especially for people that are not familiar with Clojure
2. it's impossible to run the test from an IDE like Cursive (in IntelliJ)
3. while `clojure.test/deftest` is well understood by the IDE (Cursive), `riemann.test/deftest` is not
4. it relies on some state that is defined in `riemann.bin` which is not obvious

I would like to propose a solution for this problem.

In the PR I provided (#778) I created a fixture that allows you to run the tests from an IDE using `clojure.test/deftest`.

The only one requirement is to set the environmental variable `config` what whatever you'd pass when running `riemann test riemann.config`.

Tested with `changed`, `stated-changed`, `stable`, `runs` and `moving-event-window`.

The example test could look like this:

```
(ns my-namespace
  (:require [clojure.test :refer :all]
            [riemann.test-runner :as test-runner]))

(use-fixtures :once test-runner/set-up-fixture)

(deftest some-test
  ; your test
  )

(deftest some-other-test
  ; your test
  )
```

Pull request: #778

### PR DESCRIPTION
**Pull request by andrusieczko**
Fixes #777.

### CODE REVIEW

**Comment by jamtur01** [comment]
@aphyr Any thoughts given feedback on #777 ?

**Comment by aphyr** [comment]
Sounds like 777 didn't work out as planned? NPE issues?

**Comment by mcorbin** [comment]
Maybe i missed something in my tests.

@andrusieczko : can you try to move your code in riemann.bin for example, delete the custom deftest and replace it with your fixture in riemann.test ?

**Comment by andrusieczko** [comment]
Yeah, I'll try to see what I can do this weekend.

**Comment by jamtur01** [comment]
Any follow up on this? Thanks!

**Comment by jamtur01** [comment]
Please re-open if you get a chance to come back to this! Thanks!

**Pull request closed without merging**
