### PR TITLE
refactoring send-lines fn in GraphiteUDPClient

### PR DESCRIPTION
**Pull request by ertugrulcetin**

### CODE REVIEW

**Comment by jamtur01** [comment]
I am unclear what this PR is intended to do? Can you explain? Thanks!

**Comment by ertugrulcetin** [comment]
@jamtur01 code block inside **send-line** https://github.com/riemann/riemann/blob/361973c13431da8e13e7f9e304420ca82853116c/src/riemann/graphite.clj#L54 re-defined in **send-lines** fn so I've refactored it. Just basically re-used **send-line** fn.

**Comment by ertugrulcetin** [comment]
@jamtur01 is it clear now 😊?

**Comment by jamtur01** [comment]
Thanks!

**Pull request merged**
