### PR TITLE
Don't close channel when buffer is overflowing

### PR DESCRIPTION
**Pull request by abailly**
This is a tentative fix to #686. When the channel becomes unwritable, instead of closing we now look at the response message to send: if it is a simple ACK message, we simply drop it. 

This behaviour is pretty simple and the rationale is the following:

* query responses can fill up buffer in case of slow clients, which is probably fine as long as query response do not grow too large to cause OOME, so let's keep writing those responses and let Netty's queues handle them
* when writing events' ACKs, if the buffer is filling up then this most probably means the client is not reading them properly: If it were slow, it would also probably be slow in sending events. Hence if it is not reading ACKs, don't send them back.

Comments welcomed

### CODE REVIEW

**Comment by abailly** [comment]
The latest changes pushed simply remove closing channel when `writeabilityChanged` event is fired and revert previously proposed changes.

**Comment by pyr** [comment]
This should be reopened or rebased with a single commit.

**Comment by faxm0dem** [comment]
@abailly could you rebase this please - as reported by @dch this is still not merged to master

**Comment by dch** [comment]
I ran into this issue last week, glad to find this fixes it. IMHO this would be worth rolling a 0.2.12 for, if I can help in any way to prepare that please let me know.

**Comment by abailly** [comment]
I will do it later on today (CET).

**Comment by abailly** [comment]
Done #724

**Pull request closed without merging**
