### PR TITLE
Modernize rpm packaging

### PR DESCRIPTION
**Pull request by smortex**
`lein fatrpm` does not produce a working package out-of-the-box on a recent CentOS 7 system.

This PR update the package dependencies and rely on systemd to manage the riemann service.  The generated rpm can be installed flawlessly on CentOS 7 and is running in production \o/

### CODE REVIEW

**Comment by jamtur01** [comment]
Thanks! This is awesome. I've been meaning to do this for a while.

**Comment by faxm0dem** [comment]
Hmmm this will break EL6, won't it?

**Comment by jamtur01** [comment]
@faxm0dem The JRE package upgrade or systemd?

**Comment by smortex** [comment]
Oh!  I have to admit that we do not use CentOS 6 and I completely forgot about this one.  maybe it's worth building two RPM packages, one targeted to CentOS 6 and the second targeted to CentOS 7?

**Comment by jamtur01** [comment]
@smortex Sure. That seems reasonable.

**Comment by faxm0dem** [comment]
I would be perfectly happy with either a switch `lein fatrpm --with-systemd` or a different subcommane `lein fatrpm_systemd` whatever's possible :-)

**Comment by jamtur01** [comment]
I've addressed this - the packaging system will now create two rpms - one for EL6 and one for EL7+

**Pull request merged**
