### PR TITLE
Use getWriteApiBlocking to post data to InfluxDB

### LINKED ISSUE #1027: `influxdb2` keeps accumulating background threads
**Describe the bug**
Posting to InfluxDB using `influxdb2` keeps accumulating background threads until Riemann or machine crashes.

**To Reproduce**
1.Configure Riemann to send data from few dozen reasonably active streams using `influxdb2`
2. Wait and observe accumulating threads using VisualVM.

**Expected behavior**
Stable operation.

**Screenshots**
image
image

**Background (please complete the following information):**
 - OS: CentOS 7
 - Java/JVM version 1.8.0_322-b06
 - Riemann version 0.3.8

**Additional context**
[WriteApi](https://influxdata.github.io/influxdb-client-java/influxdb-client-java/apidocs/index.html) creates a background thread and is supposed to run as a singleton. `riemann.influxdb2.post-data` creates a new instance of `WriteApi` on each invocation.
Using [WriteApiBlocking](https://influxdata.github.io/influxdb-client-java/influxdb-client-java/apidocs/index.html) fixes the issue.

### PR DESCRIPTION
**Pull request by node13h**
Fixes #1027

### CODE REVIEW

**Comment by jarpy** [comment]
What happens to Riemann when there is high latency talking to Influx?

**Comment by node13h** [comment]
@jarpy That's what `async-queue!` and `batch` are for.

**Comment by chhetripradeep** [comment]
The change looks good to me.  Thank you for fixing it.

**Comment by jamtur01** [comment]
LGTM!

**Pull request merged**
