### PR TITLE
refactor(rabbitmq-transport): configuration made even more flexible

### PR DESCRIPTION
**Pull request by serge-medvedev**

### CODE REVIEW

**Comment by faxm0dem** [comment]
Thanks for your changes. This will however break existing code. We should probably provide backwards-compatible changes

**Comment by serge-medvedev** [comment]
I supposed that it's allowed to make any changes (even breaking ones) between releases - am I wrong?

**Comment by faxm0dem** [comment]
From a semantic versioning perspective, you're right, as we're still in 0.x.y. I'd personally be in favour of breaking changes, but I'd prefer to have @aphyr @jamtur01 agree first

**Comment by aphyr** [comment]
Yeah, Riemann has a large install base: compatibility and a deprecation notice would be my preference. Folks always appreciate it when you're considerate!--KyleOn Feb 3, 2020 11:54, Fabien Wernli <notifications@github.com> wrote:From a semantic versioning perspective, you're right, as we're still in 0.x.y. I'd personally be in favour of breaking changes, but I'd prefer to have @aphyr @jamtur01 agree first

**Comment by jamtur01** [comment]
What @aphyr said. For next release I'd like backwards compatibility and a deprecation notice. x+1 releases beyond that we'd deprecate and change.

**Comment by serge-medvedev** [comment]
I do agree with your reasoning, guys, but a bit of clarification is needed.
The latest release is 0.3.5 which **doesn't** contain rabbitmq-transport functionality in it, 0.3.6 isn't out there yet so what exactly changes in this PR has to be backward compatible with?

**Comment by jamtur01** [comment]
Yeah I just realized this isn't in 0.3.5. I thought it was - mea culpa. I think we can merge without issues.

**Comment by aphyr** [comment]
Oh, if that's the case, it should be fine!On Feb 3, 2020 16:00, Serge Medvedev <notifications@github.com> wrote:I do agree with your reasoning, guys, but a bit of clarification is needed.
The latest release is 0.3.5 which doesn't contain rabbitmq-transport functionality in it, 0.3.6 isn't out there yet so what exactly changes in this PR has to be backward compatible with?

**Comment by faxm0dem** [comment]
haha same here, didn't realise this - sorry for the noise and waking everyone up

**Pull request merged**
