### PR TITLE
project: move to clojure 1.8

### PR DESCRIPTION
**Pull request by pyr**
I would love people to start giving this a shot.

### CODE REVIEW

**Comment by AeroNotix** [comment]
Any expected breakages?

**Comment by pyr** [comment]
@AeroNotix nope, but it's a big version bump and there are a lot of dependencies, so tests would be very appreciated.

**Comment by AeroNotix** [comment]
I'll check it out on gizmos I use riemann with

**Comment by pyr** [comment]
@AeroNotix there's a small warning for now since some symbols in riemann.index are now reserved in clojure 1.8 (namely: `update`) I'll adapt index later

**Pull request merged**
