### PR TITLE
Updated CHANGELOG for 0.2.11

### PR DESCRIPTION
**Pull request by jamtur01**
Ping @pyr @aphyr

### CODE REVIEW

**Comment by pyr** [comment]
LGTM

**Comment by aphyr** [comment]
Thanks @jamtur01! Great work!

Only question I'd have as a user is "what happens to my configs that used `update`"? Are they still legal? New semantics? Deprecation warning?

**Comment by jamtur01** [comment]
@aphyr Addressed.

**Comment by aphyr** [comment]
Right! Thanks James! Thanks Pierre-Yves!

**Pull request merged**
