### PR TITLE
Updates to support Java9

### PR DESCRIPTION
**Pull request by jamtur01**
All the tests pass as such. Certainly a basis.

At some point, we'll need to do something about `less-awful-ssl` and its use of `javax.xml.bind`.

### CODE REVIEW

**Comment by jamtur01** [comment]
cc @mcorbin

**Comment by jamtur01** [comment]
I'm not going to merge this until Clojure 1.9 is GA but wanted eyes on prior to that.

**Comment by mcorbin** [comment]
We should also modify the init scripts for .deb/rpm (to support both java 8 and java 9, probably by detecting the java version on the host).

**Comment by jamtur01** [comment]
@mcorbin Let me know how that looks.

**Comment by mcorbin** [comment]
The scripts seems ok to me. Regarding the java 9 jvm options, i don't know the JVM well enough to be able to say what are the best options.

**Pull request merged**
