### PR TITLE
Replace refs in moving-time-window by an atom

### PR DESCRIPTION
**Pull request by mcorbin**
Like #797, refs are replaced by an atom for performances.
I want to make some bench before merging.

### CODE REVIEW

**Comment by mcorbin** [comment]
Some numbers, using riemann-bench on my laptop with this configuration:

```clojure
(streams
 (default :ttl 300 (index))
 (moving-time-window 1)
 (moving-time-window 1)
 (moving-time-window 1)
 (moving-time-window 1)
 (moving-time-window 2)
 (moving-time-window 2)
 (moving-time-window 2)
 (moving-time-window 2))
```


bulk latency
single latency (not very useful ;) )
single throughtput
bulk throughtput

**Comment by jamtur01** [comment]
Ping @pyr @aphyr

**Comment by aphyr** [comment]
Heck yes! Great work @mcorbin, long overdue. Your benchmarks look fantastic. :)

**Comment by jamtur01** [comment]
Neato!

**Pull request merged**
