### PR TITLE
Update Docker base image to Temurin 20 JRE

### PR DESCRIPTION
**Pull request by pgilad**
Docker image was running on a very old docker image (openjdk-10) and was updated to run on latest Temurin 20 JRE running on Ubuntu 22

### CODE REVIEW

**Comment by pgilad** [comment]
Yep, works without issues for me though I haven't done extensive testing on it

**Comment by vipinvkmenon** [comment]
We are on Jre 21 so this should definitely work :)

**Comment by pgilad** [comment]
@vipinvkmenon are you sure? Even the 20 PR didn't get accepted/merged, is it worth pursuing ?

**Comment by pgilad** [comment]
Thanks @jamtur01 . Who can push a new image to `https://hub.docker.com/r/riemannio/riemann` ?

**Comment by jamtur01** [comment]
It's updated.

**Pull request merged**
