### PR TITLE
add ability to run single test (namespace), fixes #775

### LINKED ISSUE #775: running a single test (single namespace)
Hi,

There's no option to run the single test.
The only one way is to use `riemann test config-file` which will run all the tests.

I propose to change it to take an optional argument:

```
riemann test config-file namespace
```

I'm providing a pull request for that.

### PR DESCRIPTION
**Pull request by andrusieczko**

### CODE REVIEW

**Comment by mcorbin** [comment]
Nice ;) LGTM.

**Comment by jamtur01** [comment]
LGTM

**Comment by jamtur01** [comment]
Thanks!

**Comment by andrusieczko** [comment]
That was really fast, thanks! :)

**Pull request merged**
