### PR TITLE
Upgrade kinsky to 0.1.20

### PR DESCRIPTION
**Pull request by boernd**
Upgrades kafka-clients to 1.0.0. Tested with kafka 0.11.0.0 and 1.0.0

### CODE REVIEW

**Comment by mcorbin** [comment]
LGTM (but it will break users who use kafka < 0.11 no ?)

**Comment by boernd** [comment]
I think due to the version mechanism it should also work with 0.10.x brokers: https://cwiki.apache.org/confluence/display/KAFKA/Compatibility+Matrix

"Now, newer versions of the Java clients and other clients that support KIP-35 such as librdkafka are able to fall back to older request types or throw appropriate errors if functionality is not available."

**Comment by pyr** [comment]
It should be 0.1.20, not 0.1.19, I just cut a new release.

**Comment by jamtur01** [comment]
Excellent!

**Pull request merged**
