### PR TITLE
Improve the formatting of the API documentation

### PR DESCRIPTION
**Pull request by mcorbin**
I updated all the docstring to have a better formatting on the API documentation. The Riemann API is very useful but had a some formatting issues. Some example before/after this PR:

InfluxDB:

influxold
after:
influxnew

Kafka consumer:

kafkaold
after:
kafkanew

stable stream:

stableold
after:
stablenew

### CODE REVIEW

**Comment by jamtur01** [comment]
Oh very nice! Thank you @mcorbin!

**Comment by mcorbin** [comment]
I resolved the conflict

**Comment by jamtur01** [comment]
Can you rebase? I think merging your last PR messed things up.

**Comment by jamtur01** [comment]
Awesome!

**Pull request merged**
