### PR TITLE
Update packaging to produce EL8 packages too

### PR DESCRIPTION
**Pull request by faxm0dem**

### CODE REVIEW

**Comment by jamtur01** [comment]
Want to add these to the Riemann web page code as well? (https://github.com/riemann/riemann/blob/gh-pages/index.html)

**Comment by faxm0dem** [comment]
ah yes good idea, I'll make a PR

**Comment by faxm0dem** [comment]
alas that won't make any sense until the next release, will it ?

**Comment by jamtur01** [comment]
I'll cut a release shortly anyway.

**Pull request merged**
